### ISSUE TITLE
How to get to the area that is forbidden to fly?

### ISSUE THREAD

**Issue by qw9685** [DJI-Mobile-SDK-Tutorials/iOS-GSDemo#2]

**Comment by dji-dev** [comment]
Hi, please refer to this tutorial: [DJI GEO System Tutorial](https://developer.dji.com/mobile-sdk/documentation/ios-tutorials/GEODemo.html) to learn how to get the fly zone information, and unlock authorization fly zones using DJI iOS SDK. Hope this help!

**Comment by oliverou** [comment]
Seems that the issue has resolved, close it now.
