### ISSUE TITLE
Demo app doesn't work on iOS 10

### ISSUE THREAD

**Issue by nithinrgaddam** [DJI-Mobile-SDK-Tutorials/iOS-GSDemo#3]
I am running your demo application on iOS10 with a matrice 100 drone. The focus button is not able to show or focus the drone on the map.

**Comment by dji-dev** [comment]
Hi @nithinreddygaddam, thanks for your feedbacks! We will investigate this problem and get back to you soon.

**Comment by nithinreddygaddam** [comment]
![img_0100](https://cloud.githubusercontent.com/assets/2275985/19172683/0af18cbc-8bf1-11e6-9f33-738d5641eecf.PNG)
I got this error while running the app using the drone and the PC simulator. But works perfectly fine  when I use the Bridge App and connect it to the PC simulator
