### ISSUE TITLE
Pause mission and control the altitude by remote control

### ISSUE THREAD

**Issue by guicolares** [DJI-Mobile-SDK-Tutorials/iOS-GSDemo#5]
Hi, 
I'm developing a app with waypoints and for each one I need pause the mission and the user will change the altitude by remote control and then resume but when the mission is paused, it is not possible control(Change the altitude) the drone by remote control. 

I have no clue how to fix this. 

Any Ideas? 

Thanks

**Comment by dji-dev** [comment]
Hi @guicolares, it's not allowed to control the drone using remote controller during the mission execution, even it's paused. The flight mode position of the Remote Controller should be in **F** mode(For Inspire 1 series and Phantom 3 series) when the drone is executing waypoint missions. If you need to regain control of the drone(If emergency happens), you can switch the flight mode to **A** or **P** mode, but the executing mission will be stopped and cannot be resumed, you must upload and start the mission again. 

![switchflightmode-6c7add5ab9](https://cloud.githubusercontent.com/assets/11869194/19217853/fc2c73ca-8e18-11e6-8855-d1f3b355e1e7.png)

BTW, you can set the `altitude` property of **DJIWaypoint**  to change each waypoint's altitude before the mission starts. Hope this help!
