### ISSUE TITLE
Error: upload mission failed. error code -5024

### ISSUE THREAD

**Issue by tonycph** [DJI-Mobile-SDK-Tutorials/iOS-GSDemo#7]
![img_6165](https://cloud.githubusercontent.com/assets/10664603/26600286/18d720b8-45ae-11e7-8954-1c260ec1ba6d.PNG)

Hi there,

I got an error code of -5024 when I tried the demo with no modifies except the bundle id and api key. I guess my drone is connected as I can see the red plane in the map. Any suggestions?
Drone: Phantom 4 
Device: Iphone 6s version 10.3.2

**Comment by oliverou** [comment]
Hi @tonycph, are you using the DJI Assistant to simulate the GPS coordinate or test the demo outside? Have you check the [Creating a MapView and Waypoint Application](http://developer.dji.com/mobile-sdk/documentation/ios-tutorials/GSDemo.html) tutorial?  Seems like the upload mission command is sent too frequently, could you try it again?

**Comment by tonycph** [comment]
@oliverou 

Thanks for your reply. After I updated the aircraft and remote, it works great. My bad.

**Comment by oliverou** [comment]
Since this issue is resolved, close it now.

**Comment by vivekTusiyd** [comment]
> @oliverou
> 
> Thanks for your reply. After I updated the aircraft and remote, it works great. My bad.

@tonycph , I am getting same issue with iPhone 5S and Mavic . Can you guide how to fixed that issue ?
