### ISSUE TITLE
How to combine this demo with UILibarary 4.0

### ISSUE THREAD

**Issue by sqhuang** [DJI-Mobile-SDK-Tutorials/iOS-GSDemo#8]
If I just simply add the UILibarary framework into this demo and follow the instructions from UILibarary readme file, it crushed all the time.

-  Phantom 4
-  iOS 10.3
-  iiPad mini 4

**Comment by oliverou** [comment]
Hi @sqhuang , can you provide the crash logs for us to investigate the issue? Thanks!

**Comment by sqhuang** [comment]
Thank you for your reply.
I made a new copy about this demo and just added the djiuilibrary.framework to the ios-gsdemo (lateset version).  Before doing anything else, I build it and it gives the "Apple Mach-O Linker Error".
That's all I got.
Did this demo already have djiuilibrary inside? And how can I use DJIUILib in this demo?
Thanks.

**Comment by oliverou** [comment]
Hi @sqhuang, if you want to use DJI UILibrary in the GSDemo, you can check the follow steps:

1. Replace the content in the **Podfile** with the following content:
~~~
# platform :ios, '9.0'

target 'GSDemo' do
  pod 'DJI-SDK-iOS', '~> 4.1.1’
  pod ‘DJI-UILibrary-iOS’, '~> 4.1.1’
end
~~~

Then run "pod install" using Terminal in the root folder path of the GSDemo project to download and install DJI iOS SDK and DJI UILibrary in the GSDemo project.

2. Check this tutorial to import the VideoPreviewer to the GSDemo project: <http://developer.dji.com/mobile-sdk/documentation/ios-tutorials/index.html#importing-the-videoPreviewer>

After that, you should be able to use DJI UILibrary in the GSDemo without issues. Hope these helps!

**Comment by sqhuang** [comment]
Thank you. It works!
