### ISSUE TITLE
I find a typo in your tutorial article

### ISSUE THREAD

**Issue by sqhuang** [DJI-Mobile-SDK-Tutorials/iOS-GSDemo#9]
There is a typo in your tutorial article[here](https://developer.dji.com/mobile-sdk/documentation/ios-tutorials/GSDemo.html#refactoring-the-ui). Although your code here is cool I guess.

![image](https://user-images.githubusercontent.com/12937079/27830742-61ebf280-60fa-11e7-98d7-a4c1caaccf01.png)
here need update.
maybe DJIFlightControllerCurrentState ----> DJIFlightControllerState
self.droneLocation = state.aircraftLocation ----> self.droneLocation = state.aircraftLocation.coordinate

**Comment by oliverou** [comment]
Hi @sqhuang , thanks for your feedbacks! We have fixed the issue and updated the GSDemo Tutorial on the DJI developer website, please check it, thanks!

**Comment by sqhuang** [comment]
my pleasure.
But still it seems that the DJIFlightControllerCurrentState should be  DJIFlightControllerState with no "Current" I guess.
![image](https://user-images.githubusercontent.com/12937079/27835646-747a7b24-610e-11e7-8ac0-7075f3aab533.png)

**Comment by oliverou** [comment]
Hi @sqhuang , fixed it too. Please check the tutorial again! Thanks a lot!
